export const salesRoutes = [
  {
    path: 'commercial/dashboard',
    name: 'ops.commercial.dashboard',
    component: () => import('@/sales/presentation/commercial-validation/views/commercial-dashboard-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/purchase-requests',
    name: 'commercial-purchase-requests',
    component: () => import('@/sales/presentation/purchase-requests/views/request-inbox-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/purchase-requests/:id',
    name: 'commercial-purchase-request-detail',
    component: () => import('@/sales/presentation/commercial-validation/views/commercial-validation-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/manual-order-entry',
    name: 'commercial-manual-order-entry',
    component: () => import('@/sales/presentation/purchase-orders/views/create-order-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/purchase-orders',
    name: 'commercial-purchase-orders',
    component: () => import('@/sales/presentation/purchase-orders/views/orders-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/purchase-orders/:id',
    name: 'commercial-purchase-order-detail',
    component: () => import('@/sales/presentation/purchase-orders/views/order-detail-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/client-accounts',
    name: 'commercial-client-accounts',
    component: () => import('@/sales/presentation/clients/views/clients-view.vue'),
    meta: { roles: ['commercial'] },
  },
  {
    path: 'commercial/client-accounts/:id',
    name: 'commercial-client-account-profile',
    component: () => import('@/sales/presentation/clients/views/client-profile-view.vue'),
    meta: { roles: ['commercial'] },
  },
  { path: 'commercial/requests/:id', redirect: to => `/ops/commercial/purchase-requests/${to.params.id}` },
  { path: 'commercial/requests', redirect: '/ops/commercial/purchase-requests' },
  { path: 'commercial/manual-order', redirect: '/ops/commercial/manual-order-entry' },
  { path: 'orders', redirect: '/ops/commercial/purchase-orders' },
  { path: 'orders/new', redirect: '/ops/commercial/manual-order-entry' },
  { path: 'orders/:id', redirect: to => `/ops/commercial/purchase-orders/${to.params.id}` },
  { path: 'clients', redirect: '/ops/commercial/client-accounts' },
];

export const salesPortalRoutes = [
  { path: 'home', name: 'portal.home', component: () => import('@/sales/presentation/buyer-portal/views/buyer-home-view.vue') },
  { path: 'request-builder', name: 'portal.requestBuilder', component: () => import('@/sales/presentation/buyer-portal/views/buyer-request-builder-view.vue') },
  { path: 'purchase-requests', name: 'buyer-purchase-requests', component: () => import('@/sales/presentation/buyer-portal/views/buyer-requests-view.vue') },
  { path: 'purchase-requests/:id', name: 'buyer-purchase-request-detail', component: () => import('@/sales/presentation/buyer-portal/views/buyer-request-detail-view.vue') },
  { path: 'purchase-orders', name: 'buyer-purchase-orders', component: () => import('@/sales/presentation/buyer-portal/views/buyer-orders-view.vue') },
  { path: 'purchase-orders/success', name: 'buyer-purchase-orders-success', component: () => import('@/sales/presentation/buyer-portal/views/buyer-order-success-view.vue') },
  { path: 'purchase-orders/:id', name: 'buyer-purchase-order-detail', component: () => import('@/sales/presentation/buyer-portal/views/buyer-order-detail-view.vue') },
  { path: 'business-documents', redirect: '/portal/purchase-orders' },
  { path: 'payment-methods', name: 'buyer-payment-methods', component: () => import('@/sales/presentation/buyer-portal/views/buyer-payment-methods-view.vue') },
  { path: 'premium', name: 'portal.premium', component: () => import('@/sales/presentation/buyer-portal/views/buyer-premium-access-view.vue') },
  { path: 'profile', name: 'buyer-profile', component: () => import('@/sales/presentation/buyer-portal/views/buyer-profile-view.vue') },
  { path: 'legal/terms', name: 'portal.legal.terms', component: () => import('@/sales/presentation/buyer-portal/views/buyer-legal-view.vue'), props: { page: 'terms' } },
  { path: 'legal/privacy', name: 'portal.legal.privacy', component: () => import('@/sales/presentation/buyer-portal/views/buyer-legal-view.vue'), props: { page: 'privacy' } },
  { path: 'support', name: 'portal.support', component: () => import('@/sales/presentation/buyer-portal/views/buyer-support-view.vue') },
  { path: 'requests', redirect: '/portal/purchase-requests' },
  { path: 'requests/:id', redirect: to => `/portal/purchase-requests/${to.params.id}` },
  { path: 'orders', redirect: '/portal/purchase-orders' },
  { path: 'orders/success', redirect: '/portal/purchase-orders/success' },
  { path: 'orders/:id', redirect: to => `/portal/purchase-orders/${to.params.id}` },
  { path: 'documents', redirect: '/portal/purchase-orders' },
];
